Source = (Line NewLine)* [Line];

<Line> = SourceLine | Whitespace;

<SourceLine> = [Whitespace] (Comment | Label | Statement);

Comment = <#";\s*"> #"[^\n]*";

Label = <"."> Identifier [Whitespace] [Statement] [Comment];

Statement = Instruction [Whitespace] [Comment];

Instruction = Arithmetic | Move | Compare |
              Multiply | MultiplyAccumulate |
              Branch | SoftwareInterrupt | Swap |
              Load | Store | LoadMultiple | StoreMultiple;

Arithmetic         = ArithmeticOpcode [Condition] [Status] Whitespace
                     Register Separator
                     Register Separator
                     ShiftedRegisterOrImmediate;
Move               = MoveOpcode [Condition] [Status] Whitespace
                     Register Separator
                     ShiftedRegisterOrImmediate;
Compare            = CompareOpcode [Condition] Whitespace
                     Register Separator
                     ShiftedRegisterOrImmediate;
Branch             = BranchOpcode [Condition] Whitespace
                     Address;
SoftwareInterrupt  = "SWI" [Condition] Number;
Multiply           = "MUL" [Condition] [Status] Whitespace
                     Register Separator
                     Register Separator
                     Register;
MultiplyAccumulate = "MLA" [Condition] [Status] Whitespace
                     Register Separator
                     Register Separator
                     Register Separator
                     Register;
Load               = "FIXME";
Store              = "FIXME";
Swap               = "FIXME";
LoadMultiple       = "FIXME";
StoreMultiple      = "FIXME";

<ArithmeticOpcode> = "ADC" | "ADD" | "AND" | "BIC" | "EOR" | "ORR" | "RSB" |
                     "RSC" | "SBC" | "SUB";

<MoveOpcode>       = "MOV" | "MVN";

<CompareOpcode>    = "CMP" | "CMN" | "TST" | "TEQ";

<BranchOpcode>     = "B" | "BL";

Register = #"(R1[0-5])|(R[0-9])" | #"A[1-4]" | #"V[1-6]" |
           "SL" | "FP" | "IP" | "SP" | "LR" | "PC";

<ShiftedRegisterOrImmediate> = Register [Separator Shift] | Immediate;

Shift = ShiftWithArgument | "RRX";

<ShiftWithArgument> = ShiftType Whitespace (Immediate | Register);

<ShiftType> = "LSL" | "ASL" | "LSR" | "ASR" | "ROR";

Immediate = <"#"> Number;

Address = Number | Identifier;

<Number> = DecimalNumber | HexNumber;

DecimalNumber = #"\d+";

HexNumber = <"&"> #"[0-9A-F]+";

Condition = "EQ" | "NE" | "VS" | "VC" | "HI" | "LS" | "PL" | "MI" | "CS" |
            "CC" | "GE" | "GT" | "LE" | "LT";

Status = <"S">;

Identifier = #"[A-Za-z_][A-Za-z0-9_-]*";

<Separator> = <","> Whitespace;

<Whitespace> = <#"\s*">;

<NewLine> = <"\n">
